name = "AdaptiveEstimators"
uuid = "f894c1f0-37bd-4d0b-bad6-c1e4fa45af5b"
authors = ["Mandar Chitre <mandar@nus.edu.sg>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1.10"
LinearAlgebra = "1.10"
Random = "1.10"
